//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivePartiesSalesman
    {
        public int Id { get; set; }
        public string RegionCode { get; set; }
        public string PartyCode { get; set; }
        public string MainPartyCode { get; set; }
        public string EmpCode { get; set; }
    }
}
