//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRV_Masters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRV_Masters()
        {
            this.BRV_Details = new HashSet<BRV_Details>();
        }
    
        public int BRV_No { get; set; }
        public string Voucher_Ref_No { get; set; }
        public System.DateTime BRV_Date { get; set; }
        public string MainDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UpdBy { get; set; }
        public double BRV_TotalCredit { get; set; }
        public double BRV_TotalDebit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRV_Details> BRV_Details { get; set; }
    }
}
