//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chartOfAccount
    {
        public int Id { get; set; }
        public int ParentCode { get; set; }
        public int ChildCode { get; set; }
        public bool IsChild { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<int> ATypeCode { get; set; }
        public Nullable<int> SATypeCode { get; set; }
        public string ActiveFlag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UpdBy { get; set; }
        public string AllParentCode { get; set; }
    
        public virtual SubAccountType SubAccountType { get; set; }
    }
}
