//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmp
    {
        public string CompCode { get; set; }
        public string RegionCode { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpRemarks { get; set; }
        public string EmpAddress { get; set; }
        public string EmpDOB { get; set; }
        public string EmpJoiningDate { get; set; }
        public string EmpLeavingDate { get; set; }
        public string EmpDesignation { get; set; }
        public string EmpDepartment { get; set; }
        public Nullable<double> EmpBasicSalary { get; set; }
        public Nullable<double> EmpEperiance { get; set; }
        public string EmpContactNo { get; set; }
        public string EmpStatus { get; set; }
        public string EmpQualification { get; set; }
        public Nullable<double> OpeningShortCash { get; set; }
        public string DelFlag { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerm { get; set; }
        public string UpdUser { get; set; }
    }
}
