//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRV_Masters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRV_Masters()
        {
            this.CRV_Details = new HashSet<CRV_Details>();
        }
    
        public int CRV_No { get; set; }
        public string Voucher_Ref_No { get; set; }
        public System.DateTime CRV_Date { get; set; }
        public string MainDescription { get; set; }
        public double CRV_TotalDebit { get; set; }
        public double CRV_TotalCredit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UpdBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRV_Details> CRV_Details { get; set; }
    }
}
