//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRV_Details
    {
        public int Detail_Acc_ChildCode { get; set; }
        public int CRV_No { get; set; }
        public string Voucher_Ref_No { get; set; }
        public string Description { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
    
        public virtual CRV_Masters CRV_Masters { get; set; }
    }
}
