//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyIntake
    {
        public string DICode { get; set; }
        public System.DateTime DIDate { get; set; }
        public string FarmCode { get; set; }
        public Nullable<double> RawMilkQty { get; set; }
        public string UpdTerm { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdUser { get; set; }
    }
}
