//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DepartmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_DepartmentInfo()
        {
            this.HR_SubDepartmentInfo = new HashSet<HR_SubDepartmentInfo>();
        }
    
        public int SiteCode { get; set; }
        public int DepCode { get; set; }
        public string DepDescription { get; set; }
        public string DepShortName { get; set; }
    
        public virtual HR_SiteInfo HR_SiteInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_SubDepartmentInfo> HR_SubDepartmentInfo { get; set; }
    }
}
