//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DesignationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_DesignationInfo()
        {
            this.HR_EmployeeInfo = new HashSet<HR_EmployeeInfo>();
        }
    
        public int SiteCode { get; set; }
        public int DepCode { get; set; }
        public int SubDepCode { get; set; }
        public int DesCode { get; set; }
        public string DesDescription { get; set; }
        public string DesShortName { get; set; }
    
        public virtual HR_SubDepartmentInfo HR_SubDepartmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_EmployeeInfo> HR_EmployeeInfo { get; set; }
    }
}
