//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeInfo
    {
        public int SiteCode { get; set; }
        public int DepCode { get; set; }
        public int SubDepCode { get; set; }
        public int DesCode { get; set; }
        public int EmpCode { get; set; }
        public string EmpRefNo { get; set; }
        public string EmpName { get; set; }
        public string EmpFatherName { get; set; }
        public string CNIC { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public System.DateTime DOR { get; set; }
        public string PlaceOfJoining { get; set; }
        public string Active { get; set; }
        public string Status { get; set; }
        public string InactiveDescription { get; set; }
        public string Qualification { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdBy { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string DelFlag { get; set; }
    
        public virtual HR_DesignationInfo HR_DesignationInfo { get; set; }
    }
}
