//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SubDepartmentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_SubDepartmentInfo()
        {
            this.HR_DesignationInfo = new HashSet<HR_DesignationInfo>();
        }
    
        public int SiteCode { get; set; }
        public int DepCode { get; set; }
        public int SubDepCode { get; set; }
        public string SubDepDescription { get; set; }
        public string SubDepShortName { get; set; }
    
        public virtual HR_DepartmentInfo HR_DepartmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_DesignationInfo> HR_DesignationInfo { get; set; }
    }
}
