//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTableSrNo
    {
        public Nullable<long> SrNo { get; set; }
        public string InvoiceNo { get; set; }
        public string ManInvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string RegionCode { get; set; }
    }
}
