//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAS_BlazorEntities : DbContext
    {
        public FAS_BlazorEntities()
            : base("name=FAS_BlazorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<chartOfAccount> chartOfAccounts { get; set; }
        public virtual DbSet<SubAccountType> SubAccountTypes { get; set; }
        public virtual DbSet<BRV_Details> BRV_Details { get; set; }
        public virtual DbSet<BRV_Masters> BRV_Masters { get; set; }
        public virtual DbSet<CRV_Details> CRV_Details { get; set; }
        public virtual DbSet<CRV_Masters> CRV_Masters { get; set; }
    }
}
