//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recovery
    {
        public string CompanyCode { get; set; }
        public int RecoveryNo { get; set; }
        public System.DateTime RecoveryDate { get; set; }
        public string InvoiceNo { get; set; }
        public string ManInvoiceNo { get; set; }
        public string RepInvoiceNo { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CheqDate { get; set; }
        public string CheqNo { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string ClearOrBounce { get; set; }
        public Nullable<System.DateTime> ClearanceDate { get; set; }
        public string VoucherNo { get; set; }
        public string RegionCode { get; set; }
        public string MainPartyCode { get; set; }
        public string PartyCode { get; set; }
        public string EmpCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> RecAmount { get; set; }
        public Nullable<double> RecWHT { get; set; }
        public Nullable<double> RecDiscount { get; set; }
        public string DelFlag { get; set; }
        public string PostFlag { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerm { get; set; }
        public string UpdUser { get; set; }
    }
}
