//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionSetup
    {
        public string CompCode { get; set; }
        public string RegionCode { get; set; }
        public string RegionDescription { get; set; }
        public string NameAbbreviate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> RegCorporateRate { get; set; }
        public Nullable<double> UnRegCorporateRate { get; set; }
        public Nullable<double> RegRetailerRate { get; set; }
        public Nullable<double> UnRegRetailerRate { get; set; }
        public string DelFlag { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdUser { get; set; }
        public string UpdTerm { get; set; }
    }
}
