//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleInvoiceMaster()
        {
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
        }
    
        public string CompanyCode { get; set; }
        public int InvoiceNo { get; set; }
        public string ManInvoiceNo { get; set; }
        public string RepInvoiceNo { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string RegionCode { get; set; }
        public string PartyCode { get; set; }
        public string MainPartyCode { get; set; }
        public string EmpCode { get; set; }
        public string ExemptTax { get; set; }
        public string PartyStatus { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalAmt { get; set; }
        public Nullable<double> SaleTaxAmt { get; set; }
        public Nullable<double> FurtherTaxAmt { get; set; }
        public Nullable<double> IncomeTaxAmt { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<double> CashReceived { get; set; }
        public string DelFlag { get; set; }
        public string PostFlag { get; set; }
        public string TransType { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UpdTerm { get; set; }
        public Nullable<double> IncTaxAmt { get; set; }
        public Nullable<double> ExcTaxAmt { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
    }
}
