//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDetail
    {
        public string CompanyCode { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string ManInvoiceNo { get; set; }
        public string RepInvoiceNo { get; set; }
        public string PartyCode { get; set; }
        public string MainPartyCode { get; set; }
        public string TransType { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> SaleQty { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Damage { get; set; }
        public Nullable<double> Replace { get; set; }
        public Nullable<double> FOC { get; set; }
        public Nullable<double> Sampling { get; set; }
        public Nullable<double> Scheme { get; set; }
        public Nullable<double> Retrn { get; set; }
        public Nullable<double> WHT { get; set; }
        public Nullable<double> DiscPer { get; set; }
        public Nullable<double> DiscAmt { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> FurtherTaxPer { get; set; }
        public Nullable<double> FurtherTaxAmt { get; set; }
        public Nullable<double> IncTaxAmt { get; set; }
        public Nullable<double> ExcTaxAmt { get; set; }
        public Nullable<double> SaleTaxPer { get; set; }
        public Nullable<double> SaleTaxAmt { get; set; }
        public Nullable<double> ConsumerRate { get; set; }
        public Nullable<double> IncomeTaxAmt { get; set; }
        public Nullable<double> IncomeTaxPer { get; set; }
        public Nullable<double> FEDTaxAmt { get; set; }
        public Nullable<double> FEDTaxPer { get; set; }
    
        public virtual SaleInvoiceMaster SaleInvoiceMaster { get; set; }
    }
}
