//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityDB_AtTahurEntities : DbContext
    {
        public SecurityDB_AtTahurEntities()
            : base("name=SecurityDB_AtTahurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyApplication> CompanyApplications { get; set; }
        public virtual DbSet<SecurityUserAccess> SecurityUserAccesses { get; set; }
        public virtual DbSet<SecurityUserApplication> SecurityUserApplications { get; set; }
        public virtual DbSet<SecurityUserRole> SecurityUserRoles { get; set; }
        public virtual DbSet<SecurityRole> SecurityRoles { get; set; }
        public virtual DbSet<SecurityUser> SecurityUsers { get; set; }
    }
}
