//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public long ID { get; set; }
        public string UserCode { get; set; }
        public string CompCode { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string Remarks { get; set; }
        public string ActiveFlag { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string RegionCode { get; set; }
        public string EmpCode { get; set; }
        public string Status { get; set; }
    }
}
