//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortCashRecovery
    {
        public int Id { get; set; }
        public System.DateTime RecDate { get; set; }
        public string CheqNo { get; set; }
        public Nullable<System.DateTime> CheqDate { get; set; }
        public string RegionCode { get; set; }
        public string PartyCode { get; set; }
        public string EmpCode { get; set; }
        public string Type { get; set; }
        public Nullable<double> RecoveryAmount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string UpdBy { get; set; }
    }
}
